name: Issue
description: File an issue
body:
- type: checkboxes
  id: resources
  attributes:
    label: Understanding django-telegram-objects
    description: >
      In oder to avoid getting nonsense issues, please read the README, 
      [the resources in the README](https://github.com/ramiboutas/django-telegram-objects#about).
      Please confirm that you have read the resources on the package before submitting your issue.
    options:
    - label: I have read the resources.
      required: true
- type: input
  id: python_version
  attributes:
    label: Python Version
    description: Which version of Python were you using?
    placeholder: 3.9.0
  validations:
    required: false
- type: input
  id: django_version
  attributes:
    label: Django Version
    description: Which version of Django were you using?
    placeholder: 4.1.0
  validations:
    required: false
- type: input
  id: package_version
  attributes:
    label: Package Version
    description: Which version of this package were you using? If not the latest version, please check this issue has not since been resolved.
    placeholder: 0.0.1
  validations:
    required: false
- type: textarea
  id: description
  attributes:
    label: Description
    description: Please describe your issue.
  validations:
    required: true
