# Generated by Django 4.1.3 on 2022-11-30 16:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="telegram_id",
            field=models.BigIntegerField(
                help_text="Unique identifier for this chat. This number may have more than 32 significant bits and some\n        programming languages may have difficulty/silent defects in interpreting it. But it\n        has at most 52 significant bits, so a signed 64-bit integer or double-precision\n        float type are safe for storing this identifier."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                help_text="Unique identifier for this user or bot. This number may have more than 32 significant bits\n        and some programming languages may have difficulty/silent defects in interpreting\n        it. But it has at most 52 significant bits, so a 64-bit integer or double-precision\n        float type are safe for storing this identifier."
            ),
        ),
    ]
