# Generated by Django 4.1.3 on 2022-12-01 16:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_chat_telegram_id_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="all_members_are_administrators",
            field=models.BooleanField(
                blank=True,
                help_text="Optional. True, if all the members of the chat object are administrators",
                null=True,
            ),
        ),
    ]
