# Generated by Django 4.1.3 on 2022-12-01 16:58
import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_chat_all_members_are_administrators"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmember",
            name="user",
            field=auto_prefetch.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.user",
            ),
        ),
    ]
