# Generated by Django 4.1.3 on 2022-12-01 18:14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_chatmember_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmember",
            name="user",
        ),
    ]
