# Generated by Django 4.1.3 on 2022-12-01 19:17
import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_chatmember_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmemberupdated",
            name="new_chat_member",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="New information about the chat member",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.chatmember",
            ),
        ),
        migrations.AlterField(
            model_name="chatmemberupdated",
            name="old_chat_member",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="Previous information about the chat member",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.chatmember",
            ),
        ),
    ]
