# Generated by Django 4.1.3 on 2022-12-01 19:20
import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_message_new_chat_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="left_chat_participant",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.chatmember",
            ),
        ),
    ]
